source 'http://rubygems.org'

gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'dm-serializer'
gem 'dm-migrations'
gem 'json'
gem 'sinatra-json'
gem 'sinatra-flash'
gem 'warden'
gem 'pry'
gem 'curb'
